// Customer related
export const CUSTOMER_SIGNUP = 'CUSTOMER_SIGNUP';
export const CUSTOMER_LOGIN = 'CUSTOMER_LOGIN';
export const CUSTOMER_PROFILE_GET = 'CUSTOMER_PROFILE_GET';
export const CUSTOMER_PROFILE_UPDATE = 'CUSTOMER_PROFILE_UPDATE';
export const UPLOAD_CUST_IMAGE ='UPLOAD_CUST_IMAGE';
export const SEARCH_RESTAURANT = 'SEARCH_RESTAURANT';
export const GET_RESTAURANT_DETAILS = 'GET_RESTAURANT_DETAILS';
export const RESTAURANT_REVIEW_POST = 'RESTAURANT_REVIEW_POST';
export const CUSTOMER_EVENTS = "CUSTOMER_EVENTS";
export const CUSTOMER_REGISTERED_EVENTS = 'CUSTOMER_REGISTERED_EVENTS';
export const CUSTOMER_REGISTER_TO_EVENT = 'CUSTOMER_REGISTER_TO_EVENT';
export const CUSTOMER_MENU_GET = 'CUSTOMER_MENU_GET';
export const CUSTOMERS_GET = 'CUSTOMERS_GET';
export const CUSTOMERS_FOLLOWING_GET = 'CUSTOMERS_FOLLOWING_GET';
export const CUSTOMER_TO_FOLLOW  = 'CUSTOMER_TO_FOLLOW';
export const CUSTOMER_ORDERS_GET = 'CUSTOMER_ORDERS_GET';
export const CUSTOMER_ORDERS_POST = 'CUSTOMER_ORDERS_POST';
export const CUSTOMER_ALL_MESSAGES_GET = 'CUSTOMER_ALL_MESSAGES_GET';
export const CUSTOMER_MESSAGES_GET = 'CUSTOMER_MESSAGES_GET';
export const CUSTOMER_MESSAGES_PUT = 'CUSTOMER_MESSAGES_PUT';

// Restaurant related
export const RESTAURANT_SIGNUP = 'RESTAURANT_SIGNUP';
export const RESTAURANT_LOGIN = 'RESTAURANT_LOGIN';
export const RESTAURANT_PROFILE_GET = 'RESTAURANT_PROFILE_GET';
export const RESTAURANT_PROFILE_UPDATE = 'RESTAURANT_PROFILE_UPDATE';
export const UPLOAD_REST_IMAGE = 'UPLOAD_REST_IMAGE';
export const UPLOAD_DISH_IMAGE = 'UPLOAD_DISH_IMAGE';
export const RESTAURANT_REVIEW_GET = 'RESTAURANT_REVIEW_GET';
export const RESTAURANT_EVENTS_GET = 'RESTAURANT_EVENTS_GET';
export const RESTAURANT_EVENT_POST = 'RESTAURANT_EVENT_POST';
export const RESTAURANT_MENU_GET = 'RESTAURANT_MENU_GET';
export const RESTAURANT_MENU_DISH_POST = 'RESTAURANT_MENU_DISH_POST';
export const RESTAURANT_MENU_DISH_GET = 'RESTAURANT_MENU_DISH_GET';
export const RESTAURANT_MENU_DISH_DELETE = 'RESTAURANT_MENU_DISH_DELETE';
export const RESTAURANT_MENU_DISH_PUT = 'RESTAURANT_MENU_DISH_PUT';
export const RESTAURANT_ORDERS_GET = 'RESTAURANT_ORDERS_GET';
export const RESTAURANT_ORDERS_EDIT = 'RESTAURANT_ORDERS_EDIT';
export const RESTAURANT_MESSAGES_GET = 'RESTAURANT_MESSAGES_GET';
export const RESTAURANT_MESSAGES_PUT = 'RESTAURANT_MESSAGES_PUT';

// Common
export const LOGOUT = 'LOGOUT';
